theme = "hugo-now-ui"
baseurl = "https://zaviya.github.io/"
relativeurls = true
languageCode = "en-us"
title = "Zaviya Solutions Group"
googleAnalytics = "UA-58070107-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "../docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    pre = "<i class='now-ui-icons design_app'></i>"
    weight = 1
[[menu.main]]
    name = "Solutions"
    url = "/solutions"
    pre = "<i class='now-ui-icons business_bulb-63'></i>"
    weight = 1
[[menu.main]]
    name = "Partners"
    url = "/partners"
    pre = "<i class='now-ui-icons users_single-02'></i>"
    weight = 2
[[menu.main]]
    name = "Public sector"
    identifier = "public-sector"
    pre = "<i class='now-ui-icons business_badge'></i>"
    url = "/public-sector"
    weight = 3
[[menu.main]]
    name = "About Us"
    identifier = "about-us"
    pre = "<i class='now-ui-icons travel_info'></i>"
    url = "/about-us"
    weight = 4
[[menu.main]]
    name = "Careers"
    identifier = "careers"
    pre = "<i class='now-ui-icons education_hat'></i>"
    url = "/careers"
    weight = 4
[[menu.main]]
    name = "Contact"
    identifier = "contact"
    pre = "<i class='now-ui-icons ui-1_email-85'></i>"
    url = "/contact"
    weight = 5
[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/zaviyagroup"
    weight = 1
[[menu.footer]]
    identifier = "googleplus"
    pre = "<i class='fa fa-google-plus'></i>"
    url = "https://plus.google.com/111721774627079417881/"
    weight = 2
[[menu.footer]]
    identifier = "linkedin"
    pre = "<i class='fa fa-linkedin'></i>"
    url = "https://www.linkedin.com/company/zaviya-solutions-group/"
    weight = 3
[[menu.footer]]
    identifier = "facebook"
    pre = "<i class='fa fa-facebook'></i>"
    url = "https://www.facebook.com/pages/Zaviya-Solutions-Group/234018629975247"
    weight = 4


[params]
    background = "/img/bg11.jpg"
    tint = "orange"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
